#ifndef __SAMPLE_DEMUX2VDEC2VO_COMMON_H__
#define __SAMPLE_DEMUX2VDEC2VO_COMMON_H__


#define DMX2VDEC2VO_CFG_SRC_FILE_STR   "src_file"
#define DMX2VDEC2VO_CFG_SEEK_POSITION   "seek_position"
#define DMX2VDEC2VO_CFG_TEST_DURATION  "test_duration"


#endif //#define __SAMPLE_DEMUX2VDEC2VO_COMMON_H__

