#ifndef _SAMPLE_UVC2VDENC2VO_CONFIG_H_
#define _SAMPLE_UVC2VDENC2VO_CONFIG_H_

#define SAMPLE_UVC2VDENC2VO_KEY_DEV_NAME          "dev_name"
#define SAMPLE_UVC2VDENC2VO_KEY_PIC_FORMAT        "pic_format"
#define SAMPLE_UVC2VDENC2VO_KEY_CAPTURE_WIDTH     "capture_width"
#define SAMPLE_UVC2VDENC2VO_KEY_CAPTURE_HEIGHT    "capture_height"
#define SAMPLE_UVC2VDENC2VO_KEY_DISPLAY_WIDTH     "display_width"
#define SAMPLE_UVC2VDENC2VO_KEY_DISPLAY_HEIGHT    "display_height"
#define SAMPLE_UVC2VDENC2VO_KEY_TEST_DURATION     "test_duration"

#endif

